vim.keymap.set("n", "<leader><space>", ":noh<CR>", {})
vim.keymap.set("n", "oo", "o<ESC>", {})
vim.keymap.set("n", "OO", "O<ESC>", {})
vim.keymap.set("n", "ss", "i<space><ESC>", {})
vim.keymap.set("n", "a<CR>", "i<CR><ESC>", {})
vim.keymap.set("n", "<leader>h", ":<C-u>split<CR>", {})
vim.keymap.set("n", "<leader>v", ":<C-u>vsplit<CR>", {})
vim.keymap.set("n", "<S-l>", ":bnext<CR>", {})
vim.keymap.set("n", "<S-h>", ":bprevious<CR>", {})
vim.keymap.set("n", "<space>", "za", {})

-- Resize window
vim.keymap.set("n", "<C-Up>", function()
	require("smart-splits").resize_up()
end, { desc = "Resize split up" })
vim.keymap.set("n", "<C-Down>", function()
	require("smart-splits").resize_down()
end, { desc = "Resize split down" })
vim.keymap.set("n", "<C-Left>", function()
	require("smart-splits").resize_left()
end, { desc = "Resize split left" })
vim.keymap.set("n", "<C-Right>", function()
	require("smart-splits").resize_right()
end, { desc = "Resize split right" })
